baseURL = "https://flyfloor.github.io/"
languageCode = "zh-CN"
title = "braavos"
theme = "sam"
highlighter = "pygments"
PygmentsCodeFences = true
pygmentsUseClasses = true
paginate = 20
disqusShortname = "lacunafario"